NGO_CATALOG = [
    {
        "name": "Akhanda Seva for International (Operation Shanti)",
        "sector_tags": "Food Security|Education|Healthcare",
        "state": "Karnataka",
        "country": "India",
        "description": "Operation Shanti supports vulnerable communities through food, shelter, education, and medical aid programs, focusing on humanitarian relief and long-term development for underserved populations in Mysuru.",
    },
    {
        "name": "Divya Deepa Charitable Trust",
        "sector_tags": "Education|Child Welfare",
        "state": "Karnataka",
        "country": "India",
        "description": "Divya Deepa Charitable Trust works for children's welfare through education initiatives, community learning programs, and support for underprivileged families, ensuring access to schooling and development opportunities.",
    },
    {
        "name": "Divya Jyothi Charitable Trust",
        "sector_tags": "Education|Skills Development|Technology",
        "state": "Karnataka",
        "country": "India",
        "description": "Divya Jyothi Charitable Trust promotes skill development, technology education, sports, libraries, and cultural activities to empower youth and improve community development in Mysuru.",
    },
    {
        "name": "Swami Vivekananda Youth Movement",
        "sector_tags": "Healthcare|Education|Community Development",
        "state": "Karnataka",
        "country": "India",
        "description": "Swami Vivekananda Youth Movement works in healthcare, education, rural development, and research, improving health systems, empowering communities, and promoting sustainable development initiatives across underserved regions.",
    },
    {
        "name": "Brahmavidya",
        "sector_tags": "Art & Culture",
        "state": "Karnataka",
        "country": "India",
        "description": "Brahmavidya promotes classical arts education and cultural heritage through music, dance, and traditional arts training programs, supporting preservation of Indian cultural traditions.",
    },
    {
        "name": "Center For Traditional Education",
        "sector_tags": "Education|Research",
        "state": "Karnataka",
        "country": "India",
        "description": "Center For Traditional Education promotes traditional knowledge systems, curriculum research, and gurukul education methods, supporting value-based education programs.",
    },
    {
        "name": "Ganabharathi",
        "sector_tags": "Art & Culture",
        "state": "Karnataka",
        "country": "India",
        "description": "Ganabharathi promotes music, dance, cultural education, and classical arts through workshops, performances, and festivals, encouraging artistic expression and cultural heritage preservation.",
    },
    {
        "name": "Grassroots Research and Advocacy Movement (GRAAM)",
        "sector_tags": "Research|Public Policy",
        "state": "Karnataka",
        "country": "India",
        "description": "Grassroots Research and Advocacy Movement conducts governance research, public policy studies, and advocacy programs supporting evidence-based decision making and community-focused development initiatives.",
    },
    {
        "name": "Green Dot Trust",
        "sector_tags": "Elderly Welfare",
        "state": "Karnataka",
        "country": "India",
        "description": "Green Dot Trust supports senior citizens through community engagement programs, healthcare awareness, and social support initiatives for elderly wellbeing.",
    },
    {
        "name": "Indian Heritage Cities Network Foundation",
        "sector_tags": "Heritage|Culture",
        "state": "Karnataka",
        "country": "India",
        "description": "Indian Heritage Cities Network Foundation promotes preservation of cultural heritage, traditional crafts, and historic cities through research programs, cultural initiatives, and heritage conservation activities.",
    },
    {
        "name": "Ambedkar Vividoddesha Seva Samsthe",
        "sector_tags": "Social Justice",
        "state": "Karnataka",
        "country": "India",
        "description": "Ambedkar Vividoddesha Seva Samsthe works for social justice, community empowerment, and support for marginalized communities through development initiatives.",
    },
    {
        "name": "Vidyanikethan",
        "sector_tags": "Education|Nutrition|Youth Development",
        "state": "Karnataka",
        "country": "India",
        "description": "Vidyanikethan supports children and youth through education, nutrition programs, vocational training, and youth development initiatives aimed at community upliftment.",
    },
    {
        "name": "Kanasu Foundation",
        "sector_tags": "Children|Women Empowerment|Health",
        "state": "Karnataka",
        "country": "India",
        "description": "Kanasu Foundation works for children's education, women empowerment, and health awareness, supporting sustainable community welfare and social development programs.",
    },
    {
        "name": "Sarada Vilas Educational Institutions",
        "sector_tags": "Education",
        "state": "Karnataka",
        "country": "India",
        "description": "Sarada Vilas Educational Institutions promote education and literacy through schools, colleges, and academic programs focused on learning excellence and social development.",
    },
    {
        "name": "St Thomas Education Society Mysore",
        "sector_tags": "Education|Technology",
        "state": "Karnataka",
        "country": "India",
        "description": "St Thomas Education Society Mysore promotes education, ICT training, and scientific learning opportunities to enhance students' academic and professional development.",
    },
    {
        "name": "SJCE Science And Technology Entrepreneurs Park",
        "sector_tags": "Technology|Innovation",
        "state": "Karnataka",
        "country": "India",
        "description": "SJCE Science And Technology Entrepreneurs Park supports innovation, technology research, and startup incubation, encouraging entrepreneurship and scientific advancement.",
    },
    {
        "name": "Sri Bhaktimala Trust",
        "sector_tags": "Community Development",
        "state": "Karnataka",
        "country": "India",
        "description": "Sri Bhaktimala Trust organizes social welfare activities, cultural programs, and community development initiatives benefiting local communities.",
    },
    {
        "name": "The Mysore Rotary Club Charitable Trust",
        "sector_tags": "Civic Issues|Education",
        "state": "Karnataka",
        "country": "India",
        "description": "The Mysore Rotary Club Charitable Trust runs community service programs supporting education, healthcare, civic infrastructure, and social welfare projects.",
    },
    {
        "name": "Trayinyas Shrividya Foundation",
        "sector_tags": "Art & Culture|Science",
        "state": "Karnataka",
        "country": "India",
        "description": "Trayinyas Shrividya Foundation promotes arts, cultural education, and scientific awareness through community engagement programs.",
    },
    {
        "name": "Sera Je School",
        "sector_tags": "Education",
        "state": "Karnataka",
        "country": "India",
        "description": "Sera Je School supports academic development, cultural learning, and education programs for students in the Bylakuppe region.",
    },
    {
        "name": "Upadhya Art Foundation Mysore",
        "sector_tags": "Art & Culture",
        "state": "Karnataka",
        "country": "India",
        "description": "Upadhya Art Foundation Mysore promotes arts, culture, creative education, and workshops encouraging artistic expression and community participation.",
    },
    {
        "name": "Jagadguru Sri Shivarathreeshwara University",
        "sector_tags": "Education|Research",
        "state": "Karnataka",
        "country": "India",
        "description": "Jagadguru Sri Shivarathreeshwara University promotes higher education, research, scientific innovation, and community development through academic programs.",
    },
    {
        "name": "Srimad Sai Rajarajeshwari Trust",
        "sector_tags": "Rural Development|Health",
        "state": "Karnataka",
        "country": "India",
        "description": "Srimad Sai Rajarajeshwari Trust works in rural development, healthcare, education, and social upliftment, supporting marginalized communities.",
    },
    {
        "name": "Equality Institute For Thought And Action (EITA)",
        "sector_tags": "Women Empowerment|Human Rights",
        "state": "Karnataka",
        "country": "India",
        "description": "Equality Institute For Thought And Action promotes gender equality, human rights education, and social justice initiatives empowering marginalized communities.",
    },
    {
        "name": "Odanadi Seva Samsthe",
        "sector_tags": "Women Empowerment|Environment",
        "state": "Karnataka",
        "country": "India",
        "description": "Odanadi Seva Samsthe supports women empowerment, education, and environmental protection through community initiatives.",
    },
    {
        "name": "Sri Ramakrishna Ashrama",
        "sector_tags": "Education|Healthcare",
        "state": "Karnataka",
        "country": "India",
        "description": "Sri Ramakrishna Ashrama runs educational institutions, healthcare services, and tribal welfare programs promoting holistic social development.",
    },
    {
        "name": "State Resource Centre Karnataka",
        "sector_tags": "Education",
        "state": "Karnataka",
        "country": "India",
        "description": "State Resource Centre Karnataka promotes adult literacy, education, and community learning programs supporting educational development.",
    },
    {
        "name": "Sadhana",
        "sector_tags": "Children|Women Empowerment|Environment",
        "state": "Karnataka",
        "country": "India",
        "description": "Sadhana works for child development, women empowerment, environmental awareness, and community welfare programs.",
    },
    {
        "name": "Sri Guru Gnana Kendra Trust",
        "sector_tags": "Education|Healthcare",
        "state": "Karnataka",
        "country": "India",
        "description": "Sri Guru Gnana Kendra Trust conducts educational, healthcare, and community development activities.",
    },
    {
        "name": "Natana Dance Music And Drama",
        "sector_tags": "Art & Culture",
        "state": "Karnataka",
        "country": "India",
        "description": "Natana Dance Music And Drama promotes performing arts including dance, music, and theatre through cultural training, workshops, and performances.",
    },
    {
        "name": "Trust For Human And Community Development",
        "sector_tags": "Children|Community Development",
        "state": "Karnataka",
        "country": "India",
        "description": "Trust For Human And Community Development supports children's education, welfare, and community empowerment initiatives.",
    },
    {
        "name": "CRY – Child Rights and You",
        "sector_tags": "Child Rights|Education",
        "state": "Maharashtra",
        "country": "India",
        "description": "CRY – Child Rights and You protects children's rights across India, supporting grassroots organizations and improving education, healthcare, and child protection systems.",
    },
    {
        "name": "Pratham Education Foundation",
        "sector_tags": "Education|Literacy",
        "state": "Maharashtra",
        "country": "India",
        "description": "Pratham Education Foundation improves learning outcomes for underserved children through volunteer teaching programs, research, and education initiatives.",
    },
    {
        "name": "Goonj",
        "sector_tags": "Rural Development|Livelihood",
        "state": "Delhi",
        "country": "India",
        "description": "Goonj converts urban surplus materials into development resources for rural communities, supporting infrastructure and livelihood programs.",
    },
    {
        "name": "Teach For India",
        "sector_tags": "Education|Youth Development",
        "state": "Maharashtra",
        "country": "India",
        "description": "Teach For India recruits graduates to teach in under-resourced schools, reducing educational inequality.",
    },
    {
        "name": "Akshaya Patra Foundation",
        "sector_tags": "Food Security|Education",
        "state": "Karnataka",
        "country": "India",
        "description": "Akshaya Patra Foundation provides nutritious school meals, improving child nutrition, attendance, and education outcomes.",
    },
    {
        "name": "Smile Foundation",
        "sector_tags": "Education|Healthcare|Livelihood",
        "state": "Delhi",
        "country": "India",
        "description": "Smile Foundation works for education, healthcare, and livelihood development for disadvantaged communities.",
    },
    {
        "name": "SEWA – Self Employed Women’s Association",
        "sector_tags": "Women Empowerment|Livelihood",
        "state": "Gujarat",
        "country": "India",
        "description": "SEWA – Self Employed Women’s Association empowers women workers through cooperatives, financial inclusion, and social protection initiatives.",
    },
    {
        "name": "HelpAge India",
        "sector_tags": "Elderly Welfare|Healthcare",
        "state": "Delhi",
        "country": "India",
        "description": "HelpAge India supports elderly people through healthcare programs, advocacy, and livelihood support initiatives.",
    },
    {
        "name": "Barefoot College",
        "sector_tags": "Rural Development|Education",
        "state": "Rajasthan",
        "country": "India",
        "description": "Barefoot College trains rural women in solar engineering, education, and sustainable livelihoods.",
    },
    {
        "name": "Magic Bus",
        "sector_tags": "Youth Development|Education",
        "state": "Maharashtra",
        "country": "India",
        "description": "Magic Bus mentors children with life-skills education, supporting employment pathways.",
    },
    {
        "name": "WWF India",
        "sector_tags": "Environment|Conservation",
        "state": "Delhi",
        "country": "India",
        "description": "WWF India promotes wildlife conservation, biodiversity protection, and climate action programs.",
    },
    {
        "name": "Greenpeace India",
        "sector_tags": "Environment|Climate Action",
        "state": "Karnataka",
        "country": "India",
        "description": "Greenpeace India campaigns for renewable energy, environmental protection, and climate justice.",
    },
    {
        "name": "Oxfam India",
        "sector_tags": "Poverty|Gender Equality",
        "state": "Delhi",
        "country": "India",
        "description": "Oxfam India works to reduce poverty, inequality, and gender injustice through advocacy and development programs.",
    },
    {
        "name": "CARE India",
        "sector_tags": "Health|Livelihood|Women Empowerment",
        "state": "Delhi",
        "country": "India",
        "description": "CARE India improves health, education, and economic opportunities for marginalized communities.",
    },
    {
        "name": "Azim Premji Foundation",
        "sector_tags": "Education",
        "state": "Karnataka",
        "country": "India",
        "description": "Azim Premji Foundation strengthens public education systems through teacher training and research.",
    },
    {
        "name": "Habitat for Humanity India",
        "sector_tags": "Housing|Disaster Relief",
        "state": "Maharashtra",
        "country": "India",
        "description": "Habitat for Humanity India builds affordable homes, supporting vulnerable families.",
    },
    {
        "name": "Sightsavers India",
        "sector_tags": "Healthcare|Disability",
        "state": "Delhi",
        "country": "India",
        "description": "Sightsavers India prevents blindness and promotes inclusive healthcare services.",
    },
    {
        "name": "GiveIndia",
        "sector_tags": "Philanthropy|Fundraising",
        "state": "Karnataka",
        "country": "India",
        "description": "GiveIndia connects donors with verified NGOs, supporting transparent social impact giving.",
    },
    {
        "name": "Save the Children India",
        "sector_tags": "Child Welfare|Education",
        "state": "Delhi",
        "country": "India",
        "description": "Save the Children India protects vulnerable children through education, healthcare, and humanitarian programs.",
    },
    {
        "name": "WaterAid India",
        "sector_tags": "Water|Sanitation",
        "state": "Delhi",
        "country": "India",
        "description": "WaterAid India improves access to safe drinking water, sanitation, and hygiene services.",
    },
    {
        "name": "UNICEF",
        "sector_tags": "Child Welfare|Education",
        "state": "Global",
        "country": "Global",
        "description": "UNICEF works worldwide to protect children's rights and improve health, nutrition, and education.",
    },
    {
        "name": "Red Cross",
        "sector_tags": "Disaster Relief|Healthcare",
        "state": "Global",
        "country": "Global",
        "description": "Red Cross provides emergency humanitarian relief, disaster response, and healthcare services globally.",
    },
    {
        "name": "Doctors Without Borders",
        "sector_tags": "Healthcare|Emergency Relief",
        "state": "Global",
        "country": "Global",
        "description": "Doctors Without Borders provides medical aid in crisis, conflict, and disaster zones worldwide.",
    },
]

